### ISSUE TITLE
Storage limit?

### ISSUE THREAD

**Issue by jitendra1607** [mohammadnazari110/pwa_offline_video_download#1]
Have you checked the storage limit of this method? Can we store video in GB?

**Comment by mohammadnazari110** [comment]
Yes, I tried to save some video up to 500MB, but I had a problem with the < 1 GB

https://web.dev/storage-for-the-web/#:~:text=LocalStorage%20should%20be%20avoided%20because,not%20be%20used%20for%20storage.
